-- TEMPLATE port entry script: <Guest> (<source game>) in <host game>. Copy to ports/<port>/main.lua.
-- Load it in the Mesen window running the host (Script window), or headless through test_tour.lua.
--
-- Per frame (capture + reimplement architecture, docs/PLAYBOOK.md 1):
--   inputPolled  read the pad, run the guest controller, feed the host a filtered pad (EVERY button
--                explicit), steer the host's physics with the guest's numbers, update guest attacks.
--   startFrame   the host's vblank DMA is done: hide the host player's sprites and draw the guest
--                through the PPU (lua/lib/snes_obj.lua). Redraw every frame.
-- Outside gameplay: hands off. Pass the pad through, forget in-flight objects without touching RAM,
-- draw nothing, give back borrowed VRAM.
local HERE = debug.getinfo(1, "S").source:match("^@(.*[/\\])")
local kit = dofile(HERE .. "../../lua/lib/kit.lua")
local obj = dofile(KIT .. "lua/lib/snes_obj.lua")
local host = dofile(HERE .. "host.lua")
-- local guest = dofile(HERE .. "guest.lua")                  -- controller: pad + host state -> decision
-- local DATA = dofile(KIT .. "assets/<source>/<guest>.lua")   -- generated by sources/<source>/build_*.py

-- OBJ tiles the guest may overwrite: the host player's own streamed tiles plus tiles no host sprite
-- references in any stage (survey every stage before trusting a tile is free).
local TILES = {} -- TODO
local PALETTE = 0 -- TODO: the host player's OBJ palette (the guest takes it over)

local TEST_INPUT = PORT_INPUT -- headless tests supply function(frame) -> buttons
local frameNo, polledOn = 0, -1
local playing, shown, prio = false, false, 2
local layer
local decision = { pose = "stand", flip = false }

host.installSpeedOverride()

local function handsOff(pad)
  if TEST_INPUT then kit.setPad(pad, 0) end -- live: don't call setInput at all, the real pad passes
  if layer then layer:restore() end            -- give the host back the VRAM we borrowed
  layer = nil                                   -- re-read OBSEL next stage
  host.speedOverride = nil
  -- guest = <fresh controller>; must be safe to rebuild mid-action: never fire edge events
  -- (takeoff, landing, press) on the first frame after a rebuild.
end

emu.addEventCallback(kit.guard(function()
  if polledOn == frameNo then return end -- once per frame, however often the game polls
  polledOn = frameNo
  local pad = TEST_INPUT and TEST_INPUT(frameNo) or emu.getInput(0)
  playing = host.inGameplay()
  if not playing then return handsOff(pad) end
  if not host.playerInControl() then
    -- stage intro / cutscene: keep drawing the guest, but no overrides and no allocations
    if TEST_INPUT then kit.setPad(pad, 0) end
    host.speedOverride = nil
    return
  end

  -- decision = guest:update(pad, hostState)
  -- kit.setPad(decision.hostPad, 0)          -- strip what the host must not act on (our fire button...)
  -- host.speedOverride = decision.groundSpeed
  -- if decision.jumpStart then host.setVelocityY(DATA.physics.jump) end
  kit.setPad(pad, 0)
end), emu.eventType.inputPolled)

emu.addEventCallback(kit.guard(function()
  frameNo = frameNo + 1
  if not playing then return end
  if not layer then
    layer = obj.new{ tiles = TILES, palette = PALETTE }
    layer:snapshot() -- before the first write this stage
  end
  -- layer:setColors(DATA.palette)
  layer:begin()
  local hidden = layer:hide(host.isPlayerSprite)
  -- The host drew its player this frame, so draw the guest (inherits blinking, cutscenes, death).
  -- Lag frame (host skipped its OAM upload): our old sprites were reclaimed; keep last frame's answer.
  local lag = layer.reclaimed > 0 and hidden == 0
  local show = hidden > 0 or (lag and shown)
  if not lag then shown, prio = hidden > 0, layer.hiddenPrio or prio end
  if show then
    local x, y = host.playerPos()
    local cx, cy = host.camera()
    local sx, sy = x - cx, y - cy
    -- for _, t in ipairs(GFX[decision.pose]) do
    --   layer:sprite(sx + t.dx, sy + t.dy - 1, t.tile, { hflip = decision.flip, prio = prio })
    -- end                                    -- OAM y is one line above the first displayed row
  end
  layer:flush()
end), emu.eventType.startFrame)

PORT = { host = host, decision = function() return decision end } -- for tests to inspect
