"""Run a Lua script in headless Mesen 2 and report what happened.

  python tools/run_headless.py <script.lua> <rom> [--set NAME=VALUE ...] [--timeout 120] [--mesen PATH]

Mesen passes no arguments to scripts, so parameters travel as Lua globals: this writes a small wrapper
script (out/_run_<pid>.lua) that sets each --set global and then dofiles <script> by absolute path.
VALUE is used as a Lua expression when it looks like one (number, true/false/nil, {table}, "string",
or anything starting with "lua:"), otherwise it becomes a string. Relative paths resolve against the
repo root.

Mesen's stdout floods with uninitialised-read warnings, so it goes to out/mesen_stdout.txt (overwritten).
Lua errors inside callbacks are invisible headless; scripts built on lua/lib/kit.lua log them to
out/errors.txt, and this prints whatever was added to that file during the run.

Mesen is found via --mesen, else $MESEN_HEADLESS, else <repo>/mesen_headless/Mesen(.exe). Give the
headless copy the portable settings in config/mesen_headless_settings.json (docs/SETUP.md).
The script must end the run with emu.stop(code) (kit.finish); otherwise --timeout seconds ends it.
"""
import argparse, os, re, subprocess, sys, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "out")
ERRLOG = os.path.join(OUT, "errors.txt")


def lua_value(v):
    if v.startswith("lua:"):
        return v[4:]
    if re.fullmatch(r"-?(0x[0-9a-fA-F]+|\d+(\.\d+)?)", v) or v in ("true", "false", "nil"):
        return v
    if v.startswith("{") or v.startswith('"'):
        return v
    return '"' + v.replace("\\", "/").replace('"', '\\"') + '"'


def find_mesen(arg):
    for cand in [arg, os.environ.get("MESEN_HEADLESS")]:
        if cand:
            return os.path.abspath(cand)
    for name in ("Mesen.exe", "Mesen"):
        p = os.path.join(ROOT, "mesen_headless", name)
        if os.path.exists(p):
            return p
    sys.exit("Mesen not found: pass --mesen, set MESEN_HEADLESS, or unzip Mesen 2 into mesen_headless/ (docs/SETUP.md)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("script")
    ap.add_argument("rom")
    ap.add_argument("--set", action="append", default=[], metavar="NAME=VALUE")
    ap.add_argument("--timeout", type=int, default=120)
    ap.add_argument("--mesen")
    a = ap.parse_args()

    os.makedirs(OUT, exist_ok=True)
    script = os.path.abspath(a.script if os.path.isabs(a.script) else os.path.join(ROOT, a.script))
    rom = os.path.abspath(a.rom if os.path.isabs(a.rom) else os.path.join(ROOT, a.rom))
    for p in (script, rom):
        if not os.path.exists(p):
            sys.exit(f"not found: {p}")
    mesen = find_mesen(a.mesen)

    lines = ["-- generated by tools/run_headless.py"]
    for s in a.set:
        name, _, value = s.partition("=")
        if not re.fullmatch(r"[A-Za-z_]\w*", name):
            sys.exit(f"bad --set name: {name!r}")
        lines.append(f"{name} = {lua_value(value)}")
    # Top-level errors (syntax errors included) would also vanish silently: catch them here.
    errlog = ERRLOG.replace(os.sep, "/")
    lines += [
        f'local ok, err = xpcall(dofile, debug.traceback, "{script.replace(os.sep, "/")}")',
        "if not ok then",
        f'  local f = io.open("{errlog}", "a")',
        '  if f then f:write(os.date("%Y-%m-%d %H:%M:%S") .. " (loading the script) " .. tostring(err) .. "\\n"); f:close() end',
        "  emu.stop(3)",
        "end",
    ]
    wrapper = os.path.join(OUT, f"_run_{os.getpid()}.lua")
    with open(wrapper, "w") as f:
        f.write("\n".join(lines) + "\n")

    err_before = os.path.getsize(ERRLOG) if os.path.exists(ERRLOG) else 0
    t0 = time.time()
    with open(os.path.join(OUT, "mesen_stdout.txt"), "wb") as so:
        r = subprocess.run([mesen, "--testRunner", f"--timeout={a.timeout}", wrapper, rom],
                           cwd=os.path.dirname(mesen), stdout=so, stderr=subprocess.STDOUT)
    dt = time.time() - t0
    os.remove(wrapper)

    print(f"exit code {r.returncode} after {dt:.1f} s ({os.path.relpath(script, ROOT)})")
    if os.path.exists(ERRLOG) and os.path.getsize(ERRLOG) > err_before:
        with open(ERRLOG, "rb") as f:
            f.seek(err_before)
            print("NEW LUA ERRORS (out/errors.txt):")
            print(f.read().decode("utf-8", "replace"))
        sys.exit(2)
    sys.exit(0 if r.returncode == 0 else 1)


if __name__ == "__main__":
    main()
